apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lcms-pipeline
spec:
  tasks:
  - name: build
    taskRef:
      name: build-task
  - name: test
    taskRef:
      name: test-task
    runAfter:
      - build
  - name: deploy
    taskRef:
      name: deploy-task
    runAfter:
      - test